services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marcus_store_development
      DATABASE_HOST: db
    stdin_open: true
    tty: true
    depends_on:
      - db
    command: >
      bash -c "
      bundle install &&
      bin/rails db:create db:migrate &&
      bin/rails server -b 0.0.0.0"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marcus_store_development
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
